/* startup.c — vector table, reset handler, C runtime bring-up.
 *
 * Only the first 16 (core) vectors are populated.  Nothing in this firmware
 * uses an interrupt: the trigger is generated by TIM1 in hardware and the
 * command loop polls USART1, so there is no ISR to get wrong.
 */
#include <stdint.h>
#include "hw.h"

extern uint32_t _sidata, _sdata, _edata, _sbss, _ebss, _estack;

int main(void);

void Reset_Handler(void)
{
	uint32_t *src, *dst;

	/* VTOR resets to 0, which on H7 aliases the configured boot address.
	 * Point it at flash explicitly so the mapping is not load-bearing. */
	SCB_VTOR = 0x08000000UL;

	for (src = &_sidata, dst = &_sdata; dst < &_edata; )
		*dst++ = *src++;
	for (dst = &_sbss; dst < &_ebss; )
		*dst++ = 0;

	main();

	for (;;)
		;
}

static void Default_Handler(void)
{
	for (;;)
		;
}

/* Cortex-M7 core vectors.  Weak aliases are pointless here — nothing else
 * defines these — so they all land on the trap loop. */
__attribute__((section(".isr_vector"), used))
void (*const g_vectors[])(void) = {
	(void (*)(void))&_estack,	/* 0  initial MSP                  */
	Reset_Handler,			/* 1  Reset                        */
	Default_Handler,		/* 2  NMI                          */
	Default_Handler,		/* 3  HardFault                    */
	Default_Handler,		/* 4  MemManage                    */
	Default_Handler,		/* 5  BusFault                     */
	Default_Handler,		/* 6  UsageFault                   */
	0, 0, 0, 0,			/* 7-10  reserved                  */
	Default_Handler,		/* 11 SVCall                       */
	Default_Handler,		/* 12 DebugMonitor                 */
	0,				/* 13 reserved                     */
	Default_Handler,		/* 14 PendSV                       */
	Default_Handler,		/* 15 SysTick                      */
};
